sudo: required

services:
  - docker

before_install:
  - docker build -t joncovington801/workbound-client -f Dockerfile.dev .

script:
  - docker run -e CI=true joncovington801/workbound-client npm run test