version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    